<a href="https://colab.research.google.com/github/HarshSen-hub/STUD_/blob/main/Stud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:

import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("sample_student_behavior_data.csv")


print("First 5 rows:")
display(df.head())

print("\nDataset info:")
print(df.info())

print("\nStatistical summary:")
display(df.describe())

print("\nMissing values per column:")
print(df.isnull().sum())

df = df.dropna()

X = df.drop(columns=["Student_ID"] )

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nPreprocessing completed successfully!")
print("Shape of scaled data:", X_scaled.shape)

Saving sample_student_behavior_data.csv to sample_student_behavior_data.csv
First 5 rows:

,Student_ID,Attendance_Percentage,Assignment_Submission_Rate,Average_Test_Score,Participation_Score
0,S01,92,95,88,90
1,S02,85,82,80,78
2,S03,78,75,70,72
3,S04,65,60,62,58
4,S05,55,50,48,45

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  10 non-null     object
 1   Attendance_Percentage       10 non-null     int64
 2   Assignment_Submission_Rate  10 non-null     int64
 3   Average_Test_Score          10 non-null     int64
 4   Participation_Score         10 non-null     int64
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes
None

Statistical summary:

,Attendance_Percentage,Assignment_Submission_Rate,Average_Test_Score,Participation_Score
count,10.000000,10.000000,10.000000,10.000000
mean,77.200000,76.300000,72.800000,72.400000
std,13.750152,16.499495,14.649991,16.873385
min,55.000000,50.000000,48.000000,45.000000
25%,66.750000,62.500000,63.500000,59.750000
50%,80.000000,78.500000,75.000000,75.000000
75%,87.250000,88.750000,83.750000,86.000000
max,95.000000,98.000000,92.000000,94.000000

Missing values per column:
Student_ID                    0
Attendance_Percentage         0
Assignment_Submission_Rate    0
Average_Test_Score            0
Participation_Score           0
dtype: int64

Preprocessing completed successfully!
Shape of scaled data: (10, 4)

In [7]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

df.head()

,Student_ID,Attendance_Percentage,Assignment_Submission_Rate,Average_Test_Score,Participation_Score,Cluster
0,S01,92,95,88,90,2
1,S02,85,82,80,78,1
2,S03,78,75,70,72,1
3,S04,65,60,62,58,0
4,S05,55,50,48,45,0